apiVersion: v1
kind: ConfigMap
metadata:
  name: fds-config
  labels:
    {{- include "fds.labels" . | nindent 4 }}
data:
  ticket-queue-url: "{{ .Values.sqs.ticketQueueUrl }}"
  redis-host: "{{ .Values.redis.host }}"
  sqs-endpoint: "{{ .Values.sqs.endpoint }}"
  aws-region: "{{ .Values.aws.region }}"
