{{- if .Values.ruleCheckWorker.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rule-check-worker
  labels:
    {{- include "fds.labels" . | nindent 4 }}
    app: rule-check-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rule-check-worker
  minReplicas: {{ .Values.ruleCheckWorker.hpa.minReplicas }}
  maxReplicas: {{ .Values.ruleCheckWorker.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.ruleCheckWorker.hpa.targetCPU }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.ruleCheckWorker.hpa.targetMemory }}
{{- end }}
