{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: fds-secret
  labels:
    {{- include "fds.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: "{{ .Values.redis.password }}"
  {{- if .Values.aws.accessKeyId }}
  aws-access-key-id: "{{ .Values.aws.accessKeyId }}"
  aws-secret-access-key: "{{ .Values.aws.secretAccessKey }}"
  {{- end }}
{{- end }}
