apiVersion: v1
kind: Secret
metadata:
  name: fds-secret
  labels:
    {{- include "fds.labels" . | nindent 4 }}
type: Opaque
stringData:
  aws-access-key-id: "{{ .Values.aws.accessKeyId }}"
  aws-secret-access-key: "{{ .Values.aws.secretAccessKey }}"
  redis-password: "{{ .Values.redis.password }}"
