{{- range $name, $sa := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "fds.labels" $ | nindent 4 }}
  {{- if $sa.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $sa.roleArn }}
  {{- end }}
{{- end }}
