apiVersion: v1
kind: Service
metadata:
  name: sync-facade
  labels:
    {{- include "fds.labels" . | nindent 4 }}
    app: sync-facade
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.syncFacade.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.syncFacade.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sync-facade
