global:
  image:
    tag: latest  # CI overrides this

syncFacade:
  replicas: 2
  image:
    pullPolicy: Always
  hpa:
    minReplicas: 2
    maxReplicas: 10

ruleCheckWorker:
  replicas: 2
  image:
    pullPolicy: Always
  hpa:
    minReplicas: 2
    maxReplicas: 10

aws:
  region: ap-southeast-1

ingress:
  enabled: true
  host: fds-uat.example.com
