global:
  image:
    tag: latest

syncFacade:
  replicas: 1
  image:
    pullPolicy: IfNotPresent
  requestTimeoutMillis: 5000

ruleCheckWorker:
  replicas: 1
  image:
    pullPolicy: IfNotPresent
  denylist:
    refreshIntervalSeconds: 5
  hpa:
    enabled: false

aws:
  region: ap-southeast-1
  accessKeyId: test
  secretAccessKey: test

sqs:
  ticketQueueUrl: http://host.k3d.internal:4566/000000000000/fds-ticket-queue
  endpoint: http://host.k3d.internal:4566

redis:
  host: host.k3d.internal
  port: 6379
  password: ""

otel:
  enabled: true
  exporter: debug  # k3d → stdout debug
  collectorEndpoint: http://otel-collector:4317

secret:
  create: true

serviceAccounts:
  sync-facade:
    roleArn: ""
  rule-check-worker:
    roleArn: ""
  otel-collector:
    roleArn: ""

ingress:
  enabled: false
